name: Keepalive

on:
  schedule:
    - cron: '30 0 * * *'

permissions:
  contents: write

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
        with:
          days_elapsed: 40
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          auto_push: true