name: Keepalive

on:
  schedule:
    - cron: '30 0 * * *'
  workflow_dispatch:

permissions:
  actions: write

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - uses: liskin/gh-workflow-keepalive@v1
